# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt autocd beep extendedglob nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/josv/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# Set default editor to Neovim
export EDITOR=nvim

# Prompt customization
user=$'%F{blue}\ue0b6%f%K{blue}%F{black}%n%f%k%F{blue}\ue0b4%f' 
dir=$'%F{green}\ue0b6%f%K{green}%F{black} \ue5ff %~ %f%k%F{green}\ue0b4%f'
#cmd=$'%F{green}\ue0b6%f%K{green}%F{black}>%f%k%F{green}\ue0b4%f' 
cmd=$'%F{red}\uf105 %f'
newline=$'\n'

PROMPT="%B${user} ${dir} ${newline}${cmd}%b"

# Source zsh syntax highlighting and autocomplete
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
