[shell]
launch_apps_as_systemd_services = true
font_family = "JetBrainsMono Nerd Font"

[theme]
mode = "dark"
source = "community"
community_palette = "Catppuccin Mocha Mauve-Lavender"

[bar.default]
start = ["session", "spacer", "workspaces"]
center = ["clock-date", "spacer", "home", "spacer", "clock"]
end = ["volume", "brightness", "spacer", "network", "bluetooth", "spacer", "battery"]

shadow = false
margin_ends = 0
radius = 0
padding = 20

[control_center]
sidebar = "compact"
hidden_tabs = ["media", "weather"]

[widget.clock]
format = "{:%H:%M}     "
interactive = false

[widget.clock-date]
type = "clock"
format = "{:%Y-%m-%d}"
interactive = false

[widget.home]
type = "custom_button"
glyph = "menu"

[widget.home.actions]
left = "panel-toggle control-center"
