[shell]
launch_apps_as_systemd_services = true
font_family = "JetBrainsMono Nerd Font"
setup_wizard_enabled = false
polkit_agent = true

[shell.panel]
open_near_click_control_center = true
open_near_click_session = true
launcher_placement = "attached"
clipboard_placement = "attached"
polkit_placement = "attached"

[shell.launcher]
categories = false
app_grid = true

[theme]
mode = "dark"
source = "community"
community_palette = "Catppuccin Mocha Mauve-Lavender"

[bar.default]
start = ["session", "spacer", "notifications", "spacer", "clock-date", "spacer", "clock"]
center = ["workspaces"]
end = ["volume", "brightness", "spacer", "network", "bluetooth", "spacer", "battery"]
shadow = false
margin_ends = 0
radius = 0
padding = 20
thickness = 30

[control_center]
width = 600
sidebar_section = "none"

[lockscreen_widgets]
enabled = true

[lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
cx = 960.0
cy = 800.0
output = "eDP-1"
type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
    show_media = false
    show_weather = false

[lockscreen_widgets.widget.clock_main]
type     = "clock"
output   = "eDP-1"
cx         = 960.0
cy         = 400.0
box_width  = 360.0
box_height = 120.0
rotation   = 0.0

[widget.clock]
format = "{:%H:%M}"
interactive = false

[widget.clock-date]
type = "clock"
format = "{:%Y-%m-%d}"
interactive = true

[widget.session.actions]
middle = "none"

[widget.notifications.actions]
middle = "none"

[widget.workspaces.actions]
middle = "none"

[widget.clock-date.actions]
middle = "none"

[widget.volume.actions]
middle = "none"

[widget.brightness.actions]
middle = "none"

[widget.network.actions]
middle = "none"
right = "none"

[widget.bluetooth.actions]
middle = "none"

[widget.battery.actions]
middle = "none"

[bar.default.dead_zone.actions]
right = "none"

[control_center.calendar]
show_events_card = false
show_week_numbers = true
